// Full-screen post effects driven by Moth engine output (pre-rendered, see tools/prerender/run.mjs):
//
//   fork(center, dir, bias)       a split: the frame doubles into two chromatic ghosts that drift apart
//                                 along the move's two prongs and re-converge (~0.8 s). Where the doubling
//                                 is strong comes from telablur-v1 frames morphing ONE lobe into TWO; the
//                                 order the frames play in was generated by qrc-image-v1 (a quantum reservoir
//                                 trained on that fork/rejoin cycle), glitches included. Each ghost's weight
//                                 is its branch's probability.
//   collapse(center, uncertainty) a bomb's measurement: the frame pinches toward the impact (telablur-v1:
//                                 superposed cloud -> point), then a shockwave of blur-core-v1 quantum-blurred
//                                 rings pushes it outward. Strength = the outcome's normalised Shannon entropy,
//                                 i.e. how much uncertainty the measurement removed.
//
// No composer: one full-screen quad, drawn last in the transparent list, copies the frame it sits on
// (copyFramebufferToTexture) and redraws it displaced. It is invisible, so it costs nothing, when idle.
// Time comes from the stage's dt, so ?capture's virtual clock drives it; prefers-reduced-motion tones it down.

import * as THREE from 'three';
import { vfxTexture } from './sources.js';

const FORK_SECONDS = 0.85;
const PINCH_SECONDS = 0.2;
const SHOCK_SECONDS = 0.8;
const FORK_FRAMES = 5;
const COLLAPSE_FRAMES = 4;
const SHOCK_FRAMES = 8;
const FALLBACK_TOKENS = [0, 0, 1, 2, 3, 4, 4, 3, 2, 1];
const reduced = () => globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches ?? false;

export function createPostFx(stage) {
  const forkTex = vfxTexture('forkSheet', { srgb: false });
  const collapseTex = vfxTexture('collapseSheet', { srgb: false });
  const shockTex = vfxTexture('shockSheet', { srgb: false });
  let tokens = FALLBACK_TOKENS;
  if (typeof fetch !== 'undefined') {
    fetch('./generated/qrc-image-v1/fork-seq.json').then((r) => r.json()).then((d) => { if (d.tokens?.length > 8) tokens = d.tokens; }).catch(() => {});
  }

  const fb = { value: new THREE.FramebufferTexture(1, 1) };
  const U = {
    uScene: fb, uAspect: { value: 1 },
    uForkTex: forkTex.tex, uForkReady: forkTex.ready, uFork: { value: 0 }, uForkFrame: { value: 0 },
    uForkC: { value: new THREE.Vector2(0.5, 0.5) }, uForkDir: { value: new THREE.Vector2(1, 0) }, uForkBias: { value: 0.5 },
    uColTex: collapseTex.tex, uColReady: collapseTex.ready, uPinch: { value: 0 }, uPinchFrame: { value: 0 },
    uShockTex: shockTex.tex, uShockReady: shockTex.ready, uShock: { value: 0 }, uShockFrame: { value: 0 },
    uColC: { value: new THREE.Vector2(0.5, 0.5) },
  };
  const mesh = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), new THREE.ShaderMaterial({
    uniforms: U, vertexShader: VERT, fragmentShader: FRAG,
    transparent: true, blending: THREE.NoBlending, depthTest: false, depthWrite: false,
  }));
  mesh.frustumCulled = false;
  mesh.renderOrder = 999; // after everything in the scene, before the additive glitch layer (1000)
  mesh.visible = false;
  const size = new THREE.Vector2();
  mesh.onBeforeRender = (renderer) => {
    renderer.getDrawingBufferSize(size);
    const img = fb.value.image;
    if (img.width !== size.x || img.height !== size.y) {
      fb.value.dispose();
      fb.value = new THREE.FramebufferTexture(size.x, size.y);
      fb.value.minFilter = fb.value.magFilter = THREE.LinearFilter;
    }
    renderer.copyFramebufferToTexture(fb.value);
  };
  stage.scene.add(mesh);

  let fork = null; // { t, seq, amp }
  let col = null; // { t, amp }

  // center in screen uv (0..1, y up); dir in pixels (first prong -> second); bias = P(second prong)
  function forkAt(center, dir, bias = 0.5) {
    const len = Math.hypot(dir.x, dir.y) || 1;
    U.uForkC.value.copy(center);
    U.uForkDir.value.set(dir.x / len, dir.y / len);
    U.uForkBias.value = bias;
    // a window of the reservoir's generated sequence starting on a "one" frame: its own take on the fork
    const starts = tokens.map((v, i) => (v === 0 && i < tokens.length - 6 ? i : -1)).filter((i) => i >= 0);
    const s = starts.length ? starts[Math.floor(Math.random() * starts.length)] : 0;
    let seq = tokens.slice(s, s + 10);
    if (seq.length < 4) seq = FALLBACK_TOKENS;
    fork = { t: 0, seq, amp: reduced() ? 0.35 : 1 };
  }

  function collapseAt(center, uncertainty = 1) {
    U.uColC.value.copy(center);
    const u = Math.max(0, Math.min(1, uncertainty));
    col = { t: 0, amp: (reduced() ? 0.35 : 1) * u, shock: (reduced() ? 0.35 : 1) * (0.15 + 0.85 * u) };
  }

  const off = stage.onFrame((dt) => {
    U.uAspect.value = innerWidth / Math.max(1, innerHeight);
    if (fork) {
      fork.t += dt;
      const k = Math.min(1, fork.t / FORK_SECONDS);
      const pos = k * (fork.seq.length - 1);
      const i = Math.floor(pos);
      const a = fork.seq[i]; const b = fork.seq[Math.min(fork.seq.length - 1, i + 1)];
      U.uForkFrame.value = a + (b - a) * (pos - i); // tokens are ordered one..two, so blend between them
      U.uFork.value = fork.amp * Math.sin(Math.PI * k) ** 0.8;
      if (k >= 1) { fork = null; U.uFork.value = 0; }
    }
    if (col) {
      col.t += dt;
      const p = Math.min(1, col.t / PINCH_SECONDS);
      U.uPinchFrame.value = p * (COLLAPSE_FRAMES - 1);
      U.uPinch.value = col.amp * (p < 1 ? Math.sin(Math.PI * 0.5 * p) : Math.max(0, 1 - (col.t - PINCH_SECONDS) / 0.08));
      const s = Math.max(0, Math.min(1, (col.t - PINCH_SECONDS * 0.6) / SHOCK_SECONDS));
      U.uShockFrame.value = s * (SHOCK_FRAMES - 1.001);
      U.uShock.value = s > 0 ? col.shock * (1 - s) ** 1.5 : 0;
      if (col.t > PINCH_SECONDS * 0.6 + SHOCK_SECONDS) { col = null; U.uPinch.value = U.uShock.value = 0; }
    }
    mesh.visible = U.uFork.value > 1e-3 || U.uPinch.value > 1e-3 || U.uShock.value > 1e-3;
  });

  const stats = { forks: 0, collapses: 0 };
  const api = {
    fork: (...a) => { stats.forks++; forkAt(...a); },
    collapse: (...a) => { stats.collapses++; collapseAt(...a); },
    stats,
    uniforms: U,
    get active() { return mesh.visible; },
    dispose() { off(); stage.scene.remove(mesh); mesh.geometry.dispose(); mesh.material.dispose(); fb.value.dispose(); if (globalThis.__brisqueVfx?.post === api) delete globalThis.__brisqueVfx.post; },
  };
  if (typeof window !== 'undefined') (window.__brisqueVfx ??= {}).post = api; // test hook (screenshots, e2e)
  return api;
}

// world point -> screen uv (y up), for callers
export function screenUv(stage, v, out = new THREE.Vector2()) {
  const p = v.clone().project(stage.camera);
  return out.set(p.x * 0.5 + 0.5, p.y * 0.5 + 0.5);
}

const VERT = /* glsl */ `
  varying vec2 vUv;
  void main() { vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }
`;

const FRAG = /* glsl */ `
  uniform sampler2D uScene;
  uniform float uAspect;
  uniform sampler2D uForkTex; uniform float uForkReady; uniform float uFork; uniform float uForkFrame;
  uniform vec2 uForkC; uniform vec2 uForkDir; uniform float uForkBias;
  uniform sampler2D uColTex; uniform float uColReady; uniform float uPinch; uniform float uPinchFrame;
  uniform sampler2D uShockTex; uniform float uShockReady; uniform float uShock; uniform float uShockFrame;
  uniform vec2 uColC;
  varying vec2 vUv;

  vec3 scene(vec2 uv) { return texture2D(uScene, clamp(uv, vec2(0.001), vec2(0.999))).rgb; }
  // one frame of a horizontal sheet, p in [0,1]^2 (outside: 0); frames cross-fade
  float sheet(sampler2D t, float frames, float f, vec2 p) {
    if (p.x <= 0.0 || p.y <= 0.0 || p.x >= 1.0 || p.y >= 1.0) return 0.0;
    float f0 = floor(f); float f1 = min(f0 + 1.0, frames - 1.0);
    float a = texture2D(t, vec2((p.x + f0) / frames, p.y)).r;
    float b = texture2D(t, vec2((p.x + f1) / frames, p.y)).r;
    return mix(a, b, fract(f)) * smoothstep(0.5, 0.34, length(p - 0.5)); // round window hides the square
  }

  void main() {
    vec2 asp = vec2(uAspect, 1.0);
    vec2 uv = vUv;
    vec2 disp = vec2(0.0);
    float ab = 0.0; // chromatic aberration amount
    float ring = 0.0; // shockwave highlight

    // ---- bomb collapse: pinch toward the impact, then the shockwave ----
    vec2 d = (uv - uColC) * asp; // height units
    float r = length(d);
    vec2 n = d / max(r, 1e-4);
    if (uPinch > 0.0) {
      float m = uColReady > 0.5 ? sheet(uColTex, 4.0, uPinchFrame, d / 0.9 + 0.5) : exp(-r * r * 9.0);
      disp += d / asp * m * uPinch * 0.2;
      ab += m * uPinch * 0.5;
    }
    if (uShock > 0.0) {
      float m = uShockReady > 0.5 ? sheet(uShockTex, 8.0, uShockFrame, d / 2.2 + 0.5) : 0.0;
      disp -= n / asp * m * uShock * 0.08;
      ab += m * uShock * 1.6;
      ring = m * uShock;
    }

    vec2 cuv = uv + disp;
    vec2 cad = (r > 1e-4 ? n / asp : vec2(0.0)) * ab * 0.01;
    vec3 col = vec3(scene(cuv + cad).r, scene(cuv).g, scene(cuv - cad).b);
    col += vec3(1.0, 0.97, 0.9) * ring * 0.3; // pale refraction crest on the ring

    // ---- split: the frame doubles along the prongs ----
    if (uFork > 0.0) {
      vec2 f = (uv - uForkC) * asp;
      vec2 dir = uForkDir; // unit, in pixel (= height-unit) space
      vec2 local = vec2(dot(f, dir), dot(f, vec2(-dir.y, dir.x)));
      float m = uForkReady > 0.5 ? sheet(uForkTex, 5.0, uForkFrame, local / 1.1 + 0.5) : exp(-dot(local, local) * 6.0);
      float g = uFork * (0.25 + 0.75 * m) * 0.032;
      vec2 o = dir / asp * g;
      vec3 a = scene(cuv + o); // ghost shifted toward the first prong (-dir)
      vec3 b = scene(cuv - o); // ghost shifted toward the second prong (+dir)
      float wb = uForkBias; float wa = 1.0 - wb;
      vec3 doubled = (a * wa + b * wb) / max(wa + wb, 1e-4);
      // chromatic split: each ghost keeps its own fringe (warm toward one prong, cool toward the other)
      vec3 fringe = vec3(a.r, 0.5 * (a.g + b.g), b.b) * mix(vec3(1.0), vec3(1.06, 0.98, 1.06), m);
      doubled = mix(doubled, fringe, 0.8);
      float k = clamp(uFork * (0.35 + 0.65 * m) * 1.4, 0.0, 1.0);
      col = mix(col, doubled, k);
      col += vec3(0.62, 0.85, 1.0) * m * uFork * 0.07; // faint pale-blue lift where reality tears
    }
    gl_FragColor = vec4(col, 1.0);
  }
`;
